blog/app/views/main.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from flask_login import current_user

from app.extensions import db
from app.forms import PostsForm
from app.models import Posts
main = Blueprint('main',__name__)


@main.route('/',methods = ['GET','POST'])
def index():
    form = PostsForm()
    if form.validate_on_submit():
        #判断是否登录python
        if current_user.is_authenticated:
            u = current_user._get_current_object()
            p = Posts(content = form.content.data,user = u)
            db.session.add(p)
            return redirect(url_for('main.index'))
        else:
            flash('登录后才能发表')
            return redirect(url_for('user.login'))
    #读取帖子的信息
    # posts = Posts.query.filter_by(rid = 0).order_by(Posts.timestamp.desc()).all()
    page = request.args.get('page',1,type=int)
    pagination = Posts.query.filter_by(rid=0).order_by(Posts.timestamp.desc()).paginate(page,per_page=5,error_out=False)
    posts = pagination.items
    return render_template('main/index.html',form = form,posts =posts,pagination=pagination)

blog/app/views/posts.py
from flask import Blueprint, jsonify, render_template, request, g
from flask_login import current_user
import os

from app.models import Posts

posts = Blueprint('posts', __name__)


# 参数最好是类型限定，向后传递时默认是字符串
@posts.route('/collect/<int:pid>')
def collect(pid):
    # 判断是否收藏过此贴
    if current_user.is_favorite(pid):
        # 取消收藏
        current_user.del_favorite(pid)
    else:
        # 收藏
        current_user.add_favorite(pid)
    return jsonify({'result': 'ok'})

@posts.route('/myposts/<int:uid>')
def myposts(uid):

    posts = Posts.query.filter_by(rid = 0).filter_by(uid=uid).order_by(Posts.timestamp.desc())
    page = request.args.get('page', 1, type=int)
    pagination = posts.paginate(page, per_page=2, error_out=False)
    posts = pagination.items
    return render_template('posts/myposts.html', posts=posts,pagination=pagination)

blog/app/templates/main/index.html
{% extends 'common/base.html' %}

{% from 'common/macro.html' import show_pagination %}

{% block title %}首页{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}

    {# 遍历展示帖子 #}
    {% for p in posts %}
        <hr />
        <div class="media">
            <div class="media-left">
                <a href="{{ url_for('posts.myposts',uid=p.user.id) }}">
                    <img class="media-object" src="{{ url_for('static', filename='upload/'+p.user.icon) }}" alt="头像" style="height: 64px; width: 64px;">
                </a>
            </div>
            <div class="media-body">
                <div style="float: right;">{{ moment(p.timestamp).fromNow() }}</div>
                <h4 class="media-heading">{{ p.user.username }}</h4>
                {{ p.content }}
                {# 收藏功能 #}
            {% if current_user.is_authenticated %}
                <div url="{{ url_for('posts.collect', pid=p.id) }}" style="cursor: pointer;" class="collect">{% if current_user.is_favorite(p.id) %}取消收藏{% else %}收藏{% endif %}</div>
            {% endif %}
            </div>
        </div>
    {% endfor %}
    <hr />
    {# 分页构造url时的额外参数 #}
    {{ show_pagination(pagination, 'main.index', xxx='yyy') }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        $(function () {
            $('.collect').click(function () {
                _this = this
                $.get($(this).attr('url'), function () {
                    if ($(_this).text() == '收藏') {
                        $(_this).text('取消收藏')
                    } else {
                        $(_this).text('收藏')
                    }
                })
            })
        })
    </script>
{% endblock %}